boot_part_size: 200MiB

# LUKS settings
luks_partition_path: /dev/sda2
luks_name: cryptlvm
luks_passphrase: foobar1234

# LVM settings
volume_group: rootvg

lv_swap: swap
lv_swap_size: 1G

lv_home: home
lv_home_size: 2G

lv_root: root
lv_root_size: 5G
